spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@webfluxcoursecluster.ajio6ek.mongodb.net/${DB_NAME}?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: webflux-course